/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WallpapersRouteImport } from './routes/wallpapers'
import { Route as IndexRouteImport } from './routes/index'

const WallpapersRoute = WallpapersRouteImport.update({
  id: '/wallpapers',
  path: '/wallpapers',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/wallpapers': typeof WallpapersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/wallpapers': typeof WallpapersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/wallpapers': typeof WallpapersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/wallpapers'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/wallpapers'
  id: '__root__' | '/' | '/wallpapers'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WallpapersRoute: typeof WallpapersRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/wallpapers': {
      id: '/wallpapers'
      path: '/wallpapers'
      fullPath: '/wallpapers'
      preLoaderRoute: typeof WallpapersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WallpapersRoute: WallpapersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
